import Head from "next/head";
import Layout from "@/components/layout";
import CardInfo from "@/components/page/overview/card-info.component";
import Chart from "@/components/chart";
import { cardInfoModel } from "@/model/overview";

function Home() {
  return (
    <>
      <Head>
        <title>Octopus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pb-[5rem]">
        <Chart />
        <div className="flex lg:justify-between md:gap-x-4 mt-[7rem]">
          {cardInfoModel.map(({ label, value, icon, bgicon }, index) => {
            return (
              <CardInfo
                key={index}
                label={label}
                value={value}
                icon={icon}
                bgicon={bgicon}
              />
            );
          })}
        </div>
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};

export default Home;
